image:
  # Target image registry. This value is prepended to the target image repository, if set.
  # For example:
  #   registry: quay.io
  #   repository: jetstack/cert-manager-csi-driver
  # +docs:property
  # registry: quay.io

  # Target image repository.
  repository: quay.io/jetstack/cert-manager-csi-driver
  # Override the image tag to deploy by setting this variable.
  # If no value is set, the chart's appVersion is used.
  # +docs:property
  # tag: vX.Y.Z

  # Target image digest. Override any tag, if set.
  # For example:
  #   digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
  # +docs:property
  # digest: sha256:...

  # Kubernetes imagePullPolicy on Deployment.
  pullPolicy: IfNotPresent
  tag: v0.9.0
# Optional secrets used for pulling the csi-driver container image.
#
# For example:
#  imagePullSecrets:
#  - name: secret-name
imagePullSecrets: []
# Labels to apply to all resources.
commonLabels: {}
nodeDriverRegistrarImage:
  # Target image registry. This value is prepended to the target image repository, if set.
  # For example:
  #   registry: registry.k8s.io
  #   repository: sig-storage/csi-node-driver-registrar
  # +docs:property
  # registry: registry.k8s.io

  # Target image repository.
  repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
  # Override the image tag to deploy by setting this variable.
  # If no value is set, the chart's appVersion is used.
  # +docs:property
  tag: v2.10.0
  # Target image digest. Override any tag, if set.
  # For example:
  #   digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
  # +docs:property
  # digest: sha256:...

  # Kubernetes imagePullPolicy on Deployment.
  pullPolicy: IfNotPresent
livenessProbeImage:
  # Target image registry. This value is prepended to the target image repository, if set.
  # For example:
  #   registry: registry.k8s.io
  #   repository: sig-storage/livenessprobe
  # +docs:property
  # registry: registry.k8s.io

  # Target image repository.
  repository: registry.k8s.io/sig-storage/livenessprobe
  # Override the image tag to deploy by setting this variable.
  # If no value is set, the chart's appVersion is used.
  # +docs:property
  tag: v2.12.0
  # Target image digest. Override any tag, if set.
  # For example:
  #   digest: sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
  # +docs:property
  # digest: sha256:...

  # Kubernetes imagePullPolicy on Deployment.
  pullPolicy: IfNotPresent
app:
  # Verbosity of cert-manager-csi-driver logging.
  logLevel: 1 # 1-5
  # Options for CSI driver.
  driver:
    # Name of the driver to be registered with Kubernetes.
    name: csi.cert-manager.io
    # If enabled, this uses a CSI token request for creating
    # CertificateRequests. CertificateRequests are created by mounting the
    # pod's service accounts.
    useTokenRequest: false
    # Configures the hostPath directory that the driver writes and mounts volumes from.
    csiDataDir: /tmp/cert-manager-csi-driver
  # Options for the liveness container.
  livenessProbe:
    # The port that will expose the liveness of the csi-driver.
    port: 9809
  # Overrides the path to root kubelet directory in case of a non-standard Kubernetes install.
  kubeletRootDir: /var/lib/kubelet
# Optional additional annotations to add to the csi-driver DaemonSet.
daemonSetAnnotations: {}
# Optional additional annotations to add to the csi-driver pods.
podAnnotations: {}
# Optional additional labels to add to the csi-driver pods.
podLabels: {}
# Kubernetes pod resources requests/limits for cert-manager-csi-driver.
#
# For example:
#  resources:
#    limits:
#      cpu: 100m
#      memory: 128Mi
#    requests:
#      cpu: 100m
#      memory: 128Mi
resources: {}
# Kubernetes node selector: node labels for pod assignment.
# +docs:property=nodeSelector
nodeSelector:
  kubernetes.io/os: linux
# Kubernetes affinity: constraints for pod assignment.
# 
# For example:
#  affinity:
#    nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: foo.bar.com/role
#           operator: In
#           values:
#           - master
affinity: {}
# Kubernetes pod tolerations for cert-manager-csi-driver.
#
# For example:
#  tolerations:
#  - operator: "Exists"
tolerations: []
# Optional priority class to be used for the csi-driver pods.
priorityClassName: ""
openshift:
  securityContextConstraint:
    # Include RBAC to allow the DaemonSet to "use" the specified
    # SecurityContextConstraints.
    #
    # This value can either be a boolean true or false, or the string "detect".
    # If set to "detect" then the securityContextConstraint is automatically 
    # enabled for openshift installs.
    #
    # +docs:type=boolean,string,null
    enabled: detect
    # Name of the SecurityContextConstraints to create RBAC for.
    name: privileged
