apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  # Static Resources
  - path: upstream/static
    contents:
      # Cert-Manager
      - path: cert-manager
        http:
          url: https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml

  # Helm Chart Values
  - path: upstream/charts/values
    contents:
      # Cert-Manager Values
      - path: cert-manager
        http:
          url: https://cert-manager.io/docs/installation/best-practice/values.best-practice.yaml

  # Helm Charts
  - path: upstream/charts/security
    contents:
      # Cert-Manager
      - path: cert-manager
        helmChart:
          name: cert-manager
          version: "v1.15.0"
          repository:
            url: https://charts.jetstack.io
      # Cert-Manager Approver Policy
      - path: cert-manager-approver-policy
        helmChart:
          name: cert-manager-approver-policy
          version: "v0.14.1"
          repository:
            url: https://charts.jetstack.io
      # Trust Manager
      - path: trust-manager
        helmChart:
          name: trust-manager
          version: "0.11.0"
          repository:
            url: https://charts.jetstack.io
      # Cert-Manager CSI Driver
      - path: cert-manager-csi-driver
        helmChart:
          name: cert-manager-csi-driver
          version: "v0.9.0"
          repository:
            url: https://charts.jetstack.io
      # Cert-Manager CSI Driver SPIFFE
      - path: cert-manager-csi-driver-spiffe
        helmChart:
          name: cert-manager-csi-driver-spiffe
          version: "0.7.0"
          repository:
            url: https://charts.jetstack.io

