apiVersion: v1
kind: Namespace
metadata:
  name: root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: root-ca
spec:
  secretName: example-com-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: example.com
  dnsNames:
  - example.com
  - www.example.com
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io