apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: "{{ .Values.app.name }}"
  labels:
    {{- include "cert-manager-csi-driver-spiffe.labels" . | nindent 4 }}
spec:
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral
  tokenRequests:
    - audience: ""
      expirationSeconds: 3600
  requiresRepublish: true
