{{- if .Values.app.approver.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-csi-driver-spiffe.name" . }}-approver-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cert-manager-csi-driver-spiffe.name" . }}-approver
    {{- include "cert-manager-csi-driver-spiffe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.approver.metrics.service.type }}
  ports:
    - port: {{ .Values.app.approver.metrics.port }}
      targetPort: {{ .Values.app.approver.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "cert-manager-csi-driver-spiffe.name" . }}-approver
{{- end }}
